name: Kotlin
on: [ push ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - uses: gradle/gradle-build-action@v3.0.0
        with:
          gradle-version: wrapper
          arguments: build test
          build-root-directory: 2021/kotlin
