name: PHP

on: [push]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: Build
      run: |
        make --directory 2021/php build
        make --directory 2022/php build

    - name: Test
      run: |
        make --directory 2021/php test
        make --directory 2022/php test
